  float tall=200, fat =200;
  PImage img;
  int CURVEMIN=-4;
  int CURVE=-2;
  int CURVEMAX=-1;
  float curveFit=CURVE;
  int STROKEMIN=1;
  int STROKEMAX=7;
  float ctrlPointMin=5;
  float ctrlPointMax=10;
  int REDMIN=10;
  int RED=50;
  int REDMAX=200;
  int GREENMIN=50;
  int GREEN=180;
  int GREENMAX=255;
  int BLUEMIN=50;
  int BLUE=200;
  int BLUEMAX=255;
  int ALPHAMIN=100;
  int ALPH=150;
  int ALPHAMAX=200;
  float redLow=random(REDMIN,RED);
  float redHigh=random(RED,REDMAX);
  float greenLow=random(GREENMIN,GREEN);
  float greenHigh=random(GREEN,GREENMAX);
  float blueLow=random(BLUEMIN,BLUE);
  float blueHigh=random(BLUE,BLUEMAX);
  float alphaLow=random(ALPHAMIN,ALPH);
  float alphaHigh=random(ALPH,ALPHAMAX);
  int detectHeight;
  int keyIndex = -1;
  float changeChance = 0.5;
  int diam = 10;
  int out = 1;
  int R = floor(random(-255,255));
  int G = floor(random(-255,255));
  int B = floor(random(-255,255));
  int A = floor(random(-100,100));
  int disable = 0;
  float theta, r;
  int chances = 5;